### ISSUE TITLE
wrong font-family

### ISSUE THREAD

**Issue by anastasiia-emets** [itsergeysobolit/landing-elena#1]

**Comment by itsergeysobolit** [comment]
Did not quite understand what you mean. Сlarify the question, please.
Regards, Sergey

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/47434906-3185d000-d7ac-11e8-9fef-6ab0eb1aa6e2.png)
wrong font of Elena's header

**Comment by anastasiia-emets** [comment]
wrong font of Elena's header
![default](https://user-images.githubusercontent.com/40547968/47435174-b375f900-d7ac-11e8-8908-5e33966c7f2d.png)

**Comment by itsergeysobolit** [comment]
![default](https://user-images.githubusercontent.com/31821117/47435350-1798bd00-d7ad-11e8-8e68-8030742e0902.png)

**Comment by itsergeysobolit** [comment]
I have everything exactly

**Comment by rudnitskih** [comment]
Check `L` letter. It should be small I think. Anyway prefer images over fonts for all logos in this project.

**Comment by itsergeysobolit** [comment]
Yep, got it
